library(shiny)
library(tidyverse)
library(truncnorm) # truncated normal
library(igraph) # graph


# rm(list=ls()); dev.off()
setwd(dirname(rstudioapi::getSourceEditorContext()$path)) # sets the directory of this script as the current directory



##################### functions
# setwd("functions")
source(file = "functions/create_ValenceFiles.R", encoding = "UTF-8")
source(file = "functions/draw_CAM.R", encoding = "UTF-8")


vec_line_style <- c("Solid-Strong", "Solid-Weak", "Solid",
                    "Dashed", "Dashed-Weak" , "Dashed-Strong")
vec_arrow_type <- c("none", "uni")
# vec_shape <- c("positive weak", "positive", "positive strong",
#                "negative weak", "negative", "negative strong",
#                "neutral", "ambivalent")
vec_shape <- c("negative strong", "negative", "negative weak",
               "neutral",
               "positive weak", "positive", "positive strong")
# no ambivalent


## probability line style
style_prob = .3
# random arrows

## randomize labeling:
vec_labelingCAMs <- stringr::fruit



dataset <- diamonds
ui <- pageWithSidebar(
  headerPanel("Cognitive-Affective Maps - a stochastic process"),
  sidebarPanel(

    sliderInput('motivationPi', withMathJax('$$\\pi_V$$ -> define motivation (influences number of vertices)'),
                min=0, max=1,
                value=0.5),

    sliderInput('knowledgePi', withMathJax('$$\\pi_K$$ -> define knowledge (influences number of vertices)'),
                min=0, max=1,
                value=0.25),

    numericInput("attitudeMu", withMathJax('$$\\mu$$ -> define mean attitude (influences valence)'),
                                           min=-3, max=3,
                                           value=0),

    numericInput("attitudeSigma", withMathJax('$$\\sigma$$ -> define variability of attitude (influences valence)'),
                 min=0,
                 value=1),


    numericInput("edgeAlpha", withMathJax('$$\\alpha$$ -> define shape parameter 1 (influences probability for drawing an edge)'),
                 min=0.1,
                 value=2),

    numericInput("edgeBeta", withMathJax('$$\\beta$$ -> define shape parameter 2 (influences probability for drawing an edge)'),
                 min=0.1,
                 value=2),
    actionButton("randomCAM", "generate random CAM")

  ),

  mainPanel(
    uiOutput('ex2'),
    plotOutput('plot'),
    tags$br(),
    verbatimTextOutput("currentValues")
  )
)
server <- function(input, output) {


  output$ex2 <- renderUI({
    withMathJax(
      helpText('A CAM (graph) is in general defined by: $$ G = (V, E)$$, whereby V = set of vertices, E = set of edges'),
      helpText('CAM is now generated by:
               $$G = (V + K, p(E))$$'),
      helpText(', whereby we assume the following distributional assumptions:
               $$\\text{number of vertices } V \\sim Binomial(20, \\pi_V)$$
              $$\\text{> influence of knowledge on number of vertices } K \\sim Binomial(10, \\pi_K)$$
              $$\\text{> valence is influenced by the overall attitude (truncated from [-3,3]) } A \\sim N(\\mu, \\sigma)$$
               $$\\text{probability for drawing an edge } p \\sim Beta(\\alpha, \\beta)$$
               , each edge has a fixed probability of being present or absent, independently of the other edges and , the probability for generating each graph that has V vertices and E edges is (Erdos–Renyi model)
               $$p^E * (1-p)^{{V \\choose 2}-E}$$')
    )
  })



  dataset <- reactive({

    return(tmp_CAM)
  })


  observeEvent(input$randomCAM, {

    ## number of vertices
    num_V <- rbinom(n = 1, size = 20, prob = input$motivationPi)
    influence_Knowledge <- rbinom(n = 1, size = 10, prob = input$knowledgePi)

    ## overall attitude
    overall_attitude <- truncnorm::rtruncnorm(n = 1, a = -3, b = 3,
                                              mean = input$attitudeMu,
                                              sd = input$attitudeSigma)
    # print(overall_attitude)
    # > to shape probability
    shape_prob <- as.numeric(as.character(
      cut(overall_attitude, breaks = c(seq(-3.1, 3.1, by = .5)),
          seq(0, 1, length.out = 12))))

    ## number of edges
    probability_E <- rbeta(n = 1, shape1 = input$edgeAlpha, shape2 = input$edgeBeta)



    g <- igraph::sample_gnp(n = num_V + influence_Knowledge,
                            p = probability_E,
                            directed = FALSE, loops = FALSE)
    gdat <- igraph::as_data_frame(g, what = c("edges", "vertices", "both"))


    ## data set links:
    tmp_links <- data.frame(id = 1001:(1000+nrow(gdat)),
                            starting_block = gdat$from,
                            ending_block = gdat$to,
                            line_style = vec_line_style[rbinom(n = nrow(gdat), size = 5,
                                                               prob = style_prob) + 1],
                            creator = 2,
                            num = 0,
                            arrow_type = sample(x = vec_arrow_type, nrow(gdat), replace = TRUE),
                            timestamp = "00:00:00",
                            CAM = "random")

    ## data set blocks:
    tmp_blocks <- data.frame(id =  1:gorder(graph = g),
                             title = vec_labelingCAMs[1:gorder(graph = g)],
                             x_pos = 99, y_pos = 99, width = 99, height = 99,
                             shape = vec_shape[rbinom(n = gorder(graph = g), size = 6,
                                                      prob = shape_prob) + 1],
                             creator = 2,
                             num = gorder(graph = g):1,
                             comment = NA,
                             timestamp = "00:00:00",
                             modifiable = 1,
                             CAM = "random")


    tmp_blocks$participantCAM <- "aaa"
    tmp_links$participantCAM <- "aaa"

    tmp_CAM <- create_ValenceFiles(datBlocks = list(tmp_blocks), datLinks = list(tmp_links))



    output$plot <- renderPlot({
      draw_CAM(dat_merged = tmp_CAM[[3]], dat_nodes = tmp_CAM[[1]])
    }, height=700)

    output$currentValues <- renderPrint({
      cat("number of vertices \n",
          "> by motivation: ", num_V, "\n",
          "> by knowledge: ", influence_Knowledge, "\n\n",
          "the overall attitude: ", overall_attitude, "\n\n",
          "the probability to draw an edge
          between two vertices: ", probability_E)
      })

  })
}





shinyApp(ui = ui, server = server)



